# Generated by Django 3.2.9 on 2022-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20220824_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='identity',
            field=models.IntegerField(blank=True, choices=[(0, '顧客'), (1, '廠商')], default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], default=False),
        ),
    ]
