# Generated by Django 3.2.9 on 2022-08-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20220824_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identity',
            field=models.IntegerField(blank=True, choices=[(0, '顧客'), (1, '廠商')], default=True),
        ),
    ]
