# Generated by Django 3.2.9 on 2022-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_account_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='tax_ID_number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
