# Generated by Django 3.2.9 on 2022-08-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220827_0940'),
        ('partners', '0005_auto_20220824_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partner',
            new_name='Brand',
        ),
    ]
