# Generated by Django 3.2.9 on 2022-08-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_rename_partner_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='brand',
            name='tax_ID_number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
