# Generated by Django 3.2.9 on 2022-08-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20220830_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tax_ID_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
