# Generated by Django 3.2.9 on 2022-11-03 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_alter_account_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thumb_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('index_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('index_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('middle_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('middle_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ring_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ring_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('little_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('little_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('palm_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('palm_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('member', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hand_size', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
