# Generated by Django 3.2.9 on 2022-08-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_alter_brand_account'),
        ('products', '0003_auto_20220827_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='partners.brand'),
        ),
    ]
