# Generated by Django 3.2.9 on 2022-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220830_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='src/static/ring_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='threeD_model',
            field=models.FileField(blank=True, null=True, upload_to='src/static/ring_image'),
        ),
    ]
