# Generated by Django 3.2.9 on 2022-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220902_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='threeD_model',
            field=models.FileField(blank=True, null=True, upload_to='Product/'),
        ),
    ]
