# Generated by Django 3.2.9 on 2022-09-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220902_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='threeD_model',
            field=models.FileField(blank=True, null=True, upload_to='gltf/'),
        ),
    ]
