# Generated by Django 3.2.9 on 2022-09-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220905_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='src/static/media/image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='threeD_model',
            field=models.FileField(blank=True, null=True, upload_to='src/static/media/gltf/'),
        ),
    ]
